orderCarBO:
  id: '1292646512366456834'
  carNo: "\u5DDDC66666"
  mileage: 0
  mileageRecordedTime: '2020-08-19 21:33:29'
  logo: ''
  brand: "\u5954\u9A70"
  brandEn: benz
  carModelId: '60000397'
  yearModel: 0
  displacement: ''
  carModel: "\u5954\u9A70-166056 ML 400 4MATIC M276821"
  carLine: '166'
  vin: WDCDA5GBXEA338178
  engineNumber: '166056'
  produceDate: ''
  cameMileage: 0
  cameOil: ''
  quoteNoMaintainCount: 0
  extra:
    carId: '1292646512366456834'
    insuranceExpireTime: '2020-08-19 21:37:37'
    insuranceBuyTime: '2020-08-19 21:37:33'
    insuranceCode: ''
    insuranceName: "\u6C38\u8BDA"
    recentCameTime:
    cameCount: 0
    quoteNoMaintainCount: 0
    advisorCode: ''
    advisorName: ''
    lastCareTime:
    forceInsuranceExpireTime:
    forceInsuranceBuyTime:
    insuranceValidated:
    insuranceExpireMonth: -1
